%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\hmbyun\Dropbox\Work\inv-gnp-work.xlsx Worksheet:
%    SVAR Export
%
% To extend the code to different selected data or a different spreadsheet,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2017/10/05 19:29:37

%% Import the data
[tmp1, tmp2, raw] = xlsread('C:\Users\hmbyun\Dropbox\Work\inv-gnp-work.xlsx','SVAR Export');
% [~, ~, raw] = xlsread('C:\Users\hmbyun\Dropbox\Work\inv-gnp-work.xlsx','SVAR Export');

%% Replace non-numeric cells with 0.0
R = cellfun(@(x) ~isnumeric(x) || isnan(x),raw); % Find non-numeric cells
raw(R) = {0.0}; % Replace non-numeric cells

%% Create output variable
data = cell2mat(raw);

%% Allocate imported array to column variable names
DATE = data(2:end,1);
dp = data(2:end,2);
da = data(2:end,3);
h = data(2:end,4);
r = data(2:end,5);
pi = data(2:end,6);
% dp1 = data(:,7);
% dp2 = data(:,8);
% dp3 = data(:,9);
% dp4 = data(:,10);
% da1 = data(:,11);
% da2 = data(:,12);
% da3 = data(:,13);
% da4 = data(:,14);
% h1 = data(:,15);
% h2 = data(:,16);
% h3 = data(:,17);
% h4 = data(:,18);
% r1 = data(:,19);
% r2 = data(:,20);
% r3 = data(:,21);
% r4 = data(:,22);
% pi1 = data(:,23);
% pi2 = data(:,24);
% pi3 = data(:,25);
% pi4 = data(:,26);
% dda = data(:,27);
% dda1 = data(:,28);
% dda2 = data(:,29);
% dda3 = data(:,30);
% dh = data(:,31);
% dh1 = data(:,32);
% dh2 = data(:,33);
% dh3 = data(:,34);
% dr = data(:,35);
% dr1 = data(:,36);
% dr2 = data(:,37);
% dr3 = data(:,38);
% dpi = data(:,39);
% dpi1 = data(:,40);
% dpi2 = data(:,41);
% dpi3 = data(:,42);

%% Clear temporary variables
clearvars data raw R columnIndices;
